### ISSUE TITLE
Wrong Input for swaps

### ISSUE THREAD

**Issue by adilcpm** [nhuxhr/pumpfun-rs#1]
Buy Instructions takes in amount (no of tokens) + max_sol_cost

but in this SDK, for max_sol_cost, it is just buy_amount_with_slippage, which is in tokens, not in sol. 

It should be in SOL

**Solution**
- https://github.com/nhuxhr/pumpfun-rs/blob/master/crates/pumpfun/src/lib.rs#L271, substitute buy_amount with amount_sol

**Comment by nhuxhr** [comment]
Thank you for bringing this to our attention. I'll look into fixing this discrepancy in the SDK.

I'll create a PR to resolve the issue. Let me know if you have any other questions or concerns in the meantime.

**Comment by nhuxhr** [comment]
Issue resolved in commit 30813ebe08e39ae4dca9352ba0b5ccba9b5b956d
